config/routes.rb
Rails.application.routes.draw do
  resources :songs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/artists/:id' => 'artists#show', as: "artist"
  get '/artists' => 'artists#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_and_belongs_to_many :songs

  def self.order_by_name
    Artist.order("name asc")
  end

  def self.order_by_created_at
    Artist.order("created_at desc")
  end
end

app/models/song.rb
class Song < ApplicationRecord
  has_and_belongs_to_many :artists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  helper_method :sort_artists, :sort_direction
  def index
    @artists = Artist.order(sort_artists + " " + sort_direction)
  end
  def order_by_name
    @artists = Artist.order_by_name
  end
  def show
    @artist = Artist.find(params[:id])
    @songs = Song.includes(:artists).where('artists.id' => params[:id])
    @song = Song.new
  end

  private

  def sort_artists
    Artist.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :duration, :artists)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(artist_attribute, title = nil)
    title ||= artist_attribute.titleize
    direction = artist_attribute == sort_artists && sort_direction == "asc" ? "desc" : "asc"
    link_to title, :sort => artist_attribute, :direction => direction
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<h3><%= sortable "name"  %></h3>
<h3><%= sortable "created_at", "Created"  %></h3>


<% @artists.each do |artist| %>


<h1><%= link_to artist.name, artist_path(artist) %></h1>
<h2>Date of Birth: <%= artist.birth_date %></h2>
<h2>Country of Origin: <%= artist.country_of_origin %></h2>

<% end %>

app/views/artists/show.html.erb
<h1>Name: <%= @artist.name %></h1>
<h2>Date of Birth: <%= @artist.birth_date %></h2>
<h2>Country of Origin: <%= @artist.country_of_origin %></h2>

<%= render 'songs/form' %>

<%= render 'songs/index' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Songdb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<h1>New song</h1>

<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <article>
    <%= hidden_field :artist_id, @artist.id%>
  <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title, size:50, :autofocus => true %>
  </p>
  <p>
    <%= f.label :duration %> <br>
    <%= f.text_field :duration %>
  </p>

</article>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Songs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>


      <tr>
        <td><%= song.title %></td>
        <td><%= song.duration %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<%= render "index" %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>